# Generated by Django 2.0.7 on 2018-07-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('friendreq_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedby', to=settings.AUTH_USER_MODEL)),
                ('friendreq_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
